set number "行番号を表示"
set expandtab "タブ入力を複数の空白入力に置き換える"
set tabstop=4 "タブの空白の数"
set softtabstop=4 "連続した空白に対してタブキーやバックスペースキーでカーソルが動く幅"
set shiftwidth=4 "smartindentで増減する幅"
set smartindent "改行時に前の行の構文をチェックし次の行のインデントを増減する"
"cinwords = def, if ,"
set autoindent "改行時にインデントを継続する"
